### ISSUE TITLE
Backend event registration fails with no email parameter in POST

### ISSUE THREAD

**Issue by EranSch** [drastik/com.drastikbydesign.stripe#65]
While this seemingly seems much like the other ' is not of type String' errors, I think it may be different. I'm hitting this error when attempting to use the 'Submit Credit Card Event Registration' feature from a contact's summary. This error seems to be occurring regardless of whether or not the payment is attempted from within an AJAX modal or accessing the page directly. 

```
#0 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(380): CRM_Core_Error::backtrace()
#1 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(1215): CRM_Core_Error::fatal(" is not of type String")
#2 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(1149): CRM_Core_DAO::composeQuery("SELECT id\n      FROM civicrm_stripe_customers\n      WHERE email = %1", (Array:1), TRUE)
#3 /[...]/wp-content/plugins/files/civicrm/custom_ext/civicrm_stripe/CRM/Core/Payment/Stripe.php(268): CRM_Core_DAO::singleValueQuery("SELECT id\n      FROM civicrm_stripe_customers\n      WHERE email = %1", (Array:1))
#4 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Event/Form/Participant.php(1247): CRM_Core_Payment_Stripe->doDirectPayment((Array:88))
#5 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(328): CRM_Event_Form_Participant->postProcess()
#6 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(158): CRM_Core_Form->mainProcess()
#7 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(129): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Event_Form_Participant), "upload")
#8 /[...]/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Event_Form_Participant), "upload")
#9 /[...]/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_Participant), "upload")
#10 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(356): HTML_QuickForm_Page->handle("upload")
#11 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Event/Page/Tab.php(121): CRM_Core_Controller->run()
#12 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Event/Page/Tab.php(178): CRM_Event_Page_Tab->edit()
#13 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(331): CRM_Event_Page_Tab->run((Array:4), NULL)
#14 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(75): CRM_Core_Invoke::runItem((Array:12))
#15 /[...]/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#16 /[...]/wp-content/plugins/civicrm/civicrm.php(502): CRM_Core_Invoke::invoke((Array:4))
#17 [internal function](): CiviCRM_For_WordPress->invoke("")
#18 /[...]/wp-includes/plugin.php(505): call_user_func_array((Array:2), (Array:1))
#19 /[...]/wp-admin/admin.php(212): do_action("toplevel_page_CiviCRM")
#20 {main}
```

Line 3 of the trace above looks to be the source of the issue, there is a [query using the email parameter from the submission](https://github.com/drastik/civicrm_stripe/blob/4.5-1.8/CRM%2FCore%2FPayment%2FStripe.php#L268). Reviewing the POST data from this submission, there doesn't appear to be any email value included in the form. 

Is there a way to get this information and have it available for this query without the data showing up in the form? 

I don't see the `contact_id` in the form data either so how is the submission related back to the contact anyway? Is there another way to reference the contact?

**Comment by EranSch** [comment]
Been looking at this issue a little more lately and I think I've got a solid enough idea to assemble a PR for it. The only location I'm experiencing this problem is when creating a Contribution from the backend. Specifically, the 'Submit Credit Card Contribution' option under Contributions > New Contribution. 

The issue occurs after [this if/else chain](https://github.com/drastik/com.drastikbydesign.stripe/blob/4.5-1.8/CRM%2FCore%2FPayment%2FStripe.php#L252) leaves the `$email` variable empty. The issue seems to be that the contact's email address is included nowhere in the POST body. 

I'm thinking a lookup on the `contact_id` may be a suitable fix here. What do you think, @drastik?
