### ISSUE TITLE
problem when trying to register multiple participants for an event

### ISSUE THREAD

**Issue by Upperholme** [drastik/com.drastikbydesign.stripe#85]
I'me setting up and event with a price set, and want to enable the the user to register multiple participants through a conventional contribution page.

However on the registration form the payment card fields are displayed on the first page of the registration form, immediately below the fields for the first participant, so I can't move on to set up additional participants without first providing card details. 

The card details should only be collected once I have got all my participants and their particular price options set. Am I doing something wrong?

**Comment by drastik** [comment]
I'm not sure that is something this extension has control over.  This plugs into Civi as a payment processor option, but does not re-order/modify the layout of the payment form(s).

**Comment by Upperholme** [comment]
Thanks. having tested it the process appears to work in theory. However I get to the final confirmation screen and click the Continue button, and get an error : "Sorry but we are not able to provide this at the moment. Stripe.js token was not passed! Report this message to the site administrator."

**Comment by Upperholme** [comment]
Here's the detail from the CiviCRM log:

Mar 25 11:09:33  [info] $Fatal Error Details = Array
(
    [message] => Stripe.js token was not passed!  Report this message to the site administrator.
    [code] => 
)

Mar 25 11:09:33  [info] $backTrace = #0 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/Error.php(387): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/canoe/sites/default/sites/all/extensions/com.drastikbydesign.stripe-4.5-dev/CRM/Core/Payment/Stripe.php(286): CRM_Core_Error::fatal("Stripe.js token was not passed!  Report this message to the site administrator.")
#2 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Event/Form/Registration/Confirm.php(551): CRM_Core_Payment_Stripe->doDirectPayment((Array:56))
#3 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/Form.php(328): CRM_Event_Form_Registration_Confirm->postProcess()
#4 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/StateMachine.php(162): CRM_Core_Form->mainProcess()
#5 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(60): CRM_Core_StateMachine->perform(Object(CRM_Event_Form_Registration_Confirm), "next", "Next")
#6 /home/canoe/sites/default/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Event_Form_Registration_Confirm), "next")
#7 /home/canoe/sites/default/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_Registration_Confirm), "next")
#8 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/Controller.php(356): HTML_QuickForm_Page->handle("next")
#9 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(335): CRM_Core_Controller->run((Array:3), NULL)
#10 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(79): CRM_Core_Invoke::runItem((Array:15))
#11 /home/canoe/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#12 /home/canoe/sites/default/sites/all/modules/civicrm/drupal/civicrm.module(457): CRM_Core_Invoke::invoke((Array:3))
#13 [internal function](): civicrm_invoke("event", "register")
#14 /home/canoe/sites/default/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2))
#15 /home/canoe/sites/default/index.php(21): menu_execute_active_handler()
#16 {main}

**Comment by Upperholme** [comment]
OK. If I disable all other payment processors for the event and run only with Strip, it looks to work without throwing an error. I see from http://forum.civicrm.org/index.php?topic=32546.0 that this is not a new problem. When I get a moment I'll do some more investigation.
